### ISSUE TITLE
Match API/documentation with code

### ISSUE THREAD

**Issue by RenaudWasTaken** [Dubrzr/thjx2017#7]
There are multiple places where the descibed behavior in the documentation
does not match the implementation (IE: auto_nose / auto_mur, which promise a random move
but this is not the case).

This should be either fixed in the documentation or the code.
Current implementation for auto_nose seems like  a good idea (worse possible move) but it might be a good idea to think about how auto_mur acts.

**Comment by tgy** [comment]
Using random moves for `auto_mur` or `auto_nose` was a bad idea. That's how I thought about when I first wrote the API but it makes things more complicated since the results become non deterministic and harder to replicate. My personal thought is that we should keep things the way they are (playing the worst possible move) and change the documentation.

**Comment by tgy** [comment]
I created PR #8 that fixes the documentation.

**Comment by RenaudWasTaken** [comment]
Fixed in 9b8a168a7a761f00b20110acfb943a630c473ff6

**Comment by RenaudWasTaken** [comment]
After thinking it through, changed the behavior to end the game and put a timeout attribute
